name: Publish Package to GitHub NPM Registry

on: 
  release:
    types: published
    
jobs:
    npm-package:
      permissions: 
        packages: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@4
        - name: Setup NodeJS
          uses: actions/setup-node@v4
          with:
            version: '20.x'
            registry-url: "https://npm.pkg.github.com/"
        - name: Install Dependencies
          run: npm install
        - name: Publish to Github NPM Repository
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
